version: '3.8'

services:
  # Backend PHP
  app:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    image: sinilai-backend
    container_name: sinilai-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sinilai-network

  # Backend Nginx
  webserver:
    image: nginx:alpine
    container_name: sinilai-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sinilai-network

  # Frontend PHP (pakai container PHP yang sama)
  frontend-app:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    image: sinilai-frontend
    container_name: sinilai-fe-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - sinilai-network

  # Frontend Nginx
  frontend-web:
    image: nginx:alpine
    container_name: sinilai-fe-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/var/www
      - ./docker/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sinilai-network

  # MySQL
  db:
    image: mysql:8.0
    container_name: sinilai-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sinilai2
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - sinilai-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sinilai-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - sinilai-network

networks:
  sinilai-network:
    driver: bridge

volumes:
  dbdata:
    driver: local